POST http://localhost:3000/api/post
Content-Type:  application/json

{
    "name":"Kerem 2042430",
    "age":21
}

###

GET http://localhost:3000/api/getAll

###

GET http://localhost:3000/api/getOne/6526ee91cd8779a09eeaedbc

###

PATCH  http://localhost:3000/api/update/6526ee91cd8779a09eeaedbc
Content-Type: application/json

{
    "name":"Kerem1111",
    "age":34
}

###

DELETE  http://localhost:3000/api/delete/6526f00f70bd6994b53c1f87

#############################################################

POST http://localhost:3000/complainant/signUp
Content-Type:  application/json

{
    "name":"Kerem",
    "surname":"Kaplan",
    "gender":"Male",
    "email":"kerem@mail.com",
    "password":"kerem123",
    "phoneNumber":"05555555555",
    "nationality":"Turk",
    "dateOfBirth":"2002-15-01"
}

###

POST http://localhost:3000/corporation/signUp
Content-Type:  application/json

{
    "name":["Eshot"]
}

###
POST http://localhost:3000/login
Content-Type:  application/json

{
    "email":"emel@gmail.com",
    "sifre":"emel"
}

###
POST http://localhost:3000/sikayetci/sign-up
Content-Type: application/json 

{
    "isim": "aaaa",
    "soyisim": "ffffff",
    "cinsiyet": "Kadın",
    "dogumTarihi": 2004,
    "uyruk": "Türk",
    "tcveyapasaport": "1111111111",
    "email": "havvanur@gmail.com",
    "sifre": "havvanur",
    "telefonNo": "03333333333",
    "rol": "şikayetçi"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"kerem@gmail.com",
    "sifre":"kerem" 
}

###

GET http://localhost:3000/gozlemci/sikayet-goruntule/652ae92330f6a6cf8134e602

###
GET http://localhost:3000/gozlemci/oneri-goruntule/652ae92330f6a6cf8134e602
###
GET http://localhost:3000/gozlemci/istek-goruntule/652ae92330f6a6cf8134e602
###
GET http://localhost:3000/sikayetci/gecmis-sikayet/652ae8e906aa041cb56b06c7
Content-Type: application/json

{
    "rol":"şikayetçi"
}
###
GET http://localhost:3000/gozlemci/oneri-goruntule/652ae92330f6a6cf8134e602
Content-Type: application/json

{
    "rol":"gozlemci"
}
###
POST  http://localhost:3000/sikayetci/sikayet-gonder
Content-Type: application/json

{ 
    "sikayetciId":"652ea3df12a55ba0638ba94e",
    "gozlemciId":"652ae92330f6a6cf8134e602",
    "oy":4,
    "sikayetIcerigi":{
    
     }

}
###
POST  http://localhost:3000/sikayetci/oneri-gonder
Content-Type: application/json

{ 
    "sikayetciId":"652ea3df12a55ba0638ba94e",
    "gozlemciId":"652ae92330f6a6cf8134e602",
    "oneriIcerigi":{
    "oneriKonu-1":"Oneri1"
     }

}
###
POST  http://localhost:3000/sikayetci/istek-gonder
Content-Type: application/json

{ 
    "sikayetciId":"652ea3df12a55ba0638ba94e",
    "gozlemciId":"652ae92330f6a6cf8134e602",
    "istekIcerigi":{
   
     }

}
###

POST http://localhost:3000/soap-request

{
    "TCKimlikNo":10250719522,
        "Ad":"Kerem",
        "Soyad":"Kaplan",
        "DogumYili":2002
}

###

POST http://localhost:3000/gozlemci/sikayet-ister-ekle/652ae92330f6a6cf8134e602
Content-Type: application/json

{
    
    "isterler":{
        "sikayetKonusu":["Sorunlu Araç","Trafik kuralı ihlali","Durak Problemi"],
        "oyMiktarı":5
    }
}
###
POST http://localhost:3000/gozlemci/oneri-ister-ekle/652ae92330f6a6cf8134e602
Content-Type: application/json

{
    "isterler":{
        "oneriKonusu":["Durak","Otobüs"],
        "oneriDetayi":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        
    }
}

###
POST http://localhost:3000/gozlemci/oneri-ister-ekle/652ae92330f6a6cf8134e602
Content-Type: application/json

{
    "isterler":{
        "oneriKonusu":["Durak","Otobüs"],
        "oneriDetayi":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        
    }
}

###
POST http://localhost:3000/gozlemci/istek-ister-ekle/652ae92330f6a6cf8134e602
Content-Type: application/json

{
    "isterler":{
        "istekKonusu":["Durak","Otobüs"],
        "IstekDetayi":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        
    }
}

###
GET http://localhost:3000/sikayetci/gecmis-sikayet/652ea3df12a55ba0638ba94e
Content-Type: application/json 
 
###
GET http://localhost:3000/gozlemci/sikayetIsterler/652ae92330f6a6cf8134e602
Content-Type: application/json

### 
GET http://localhost:3000/gozlemci/oneriIsterler/652ae92330f6a6cf8134e602
Content-Type: application/json
###
GET http://localhost:3000/gozlemci/istekIsterler/652ae92330f6a6cf8134e602
Content-Type: application/json

###
GET http://localhost:3000/gozlemci/sikayet-goruntule/652ae92330f6a6cf8134e602
Content-Type: application/json